### ISSUE TITLE
Private Bookmarks appearing in Recently Bookmarked list

### ISSUE THREAD

**Issue by 1000HBOB** [rharel/webext-private-bookmarks#107]
For suggestions, please fill in:
 - What you wish you could do and why: ?
 - What you propose as a solution: ?

For bug reports, please fill in:
 - Firefox version: ?
 - Operating system: ?
 - Steps to reproduce: ?
 - What was the expected behavior: ?
 - What was the actual behavior: ?

It is assumed that you are using the latest version of Private Bookmarks.
The benefits of Private Bookmarks is minimal as all bookmarks appear in the Recently Bookmarked List. If you delete the bookmark from that list, it removes the bookmark entirely including those in the private folder. Is there any way to hide/remove the Recent Bookmarks list
(I'm Using Firefox Quantum 66.03)

**Comment by rharel** [comment]
Using Firefox Quantum 66.0.3, the bookmarks disappear from the Recently Bookmarked list once Private Bookmarks is locked. If your issue is that they appear in that list while Private Bookmarks is unlocked, then we are out of luck as Firefox does not give extensions control over that aspect.

**Comment by rharel** [comment]
P.S. Could you explain why this detracts from PB's benefit? I mean while unlocked the idea is that your private bookmarks are just like any other bookmark, and so are accessible from all facets of the browser including auto-completion, bookmark menus etc. It is assumed that as long as they are unlocked only you and other people you don't mind sharing your private bookmarks with have access to the browser and once you are done you lock the bookmarks again.

**Comment by 1000HBOB** [comment]
Many thanks for this – I’m sorry for the delay in replying. 

 

You are right of course. I’m afraid that my computer tends to stress me out  - and as a result I manage to confuse myself and not see the wood for the trees.

 

Thanks again for your help

Bob
