### ISSUE TITLE
Can't import encrypted bookmarks

### ISSUE THREAD

**Issue by AverageUser2** [rharel/webext-private-bookmarks#113]
- Firefox version: 68.0.1
 - Operating system: Windows 10 1903
 - Steps to reproduce: I selected the backup file, typed in it's password and tried to restore the bookmarks
 - What was the expected behavior: import the bookmarks
 - What was the actual behavior: The import button doesn't work

![immagine](https://user-images.githubusercontent.com/53372753/61995186-1ae70f00-b085-11e9-9a2b-35ab7aed8211.png)

**Comment by rharel** [comment]
I assume you unlocked before trying to import? See the instruction: "Importing requires unlocked bookmarks"

**Comment by AverageUser2** [comment]
I must have accidentally closed the private window when i was trying to import the bookmarks thus locking the bookmarks, definitely my fault
