### ISSUE TITLE
access boomarks on new browser

### ISSUE THREAD

**Issue by dammit1964** [rharel/webext-private-bookmarks#126]
I was using PM on Tor Browser without issue. Refreshed Tor, and PM was gone. Discovered that PM will not work with latest version of Tor. I did not back up my bookmarks. I have a backup of the profile. Is there a way to access my bookmarks in a new browser?

**Comment by rharel** [comment]
1. In your backup profile folder, under `browser-extension-data\private-bookmarks@rharel` there should be a file `storage.js`. Open it in a plain text editor (like notepad or notepad++)
2. Inside you should see something like:
`{...,"back_folder":{"signature":{"iv":"A","ciphertext":"B"},"bookmarks":{"iv":"C","ciphertext":"D"},...}}`

Where `A`, `B`, `C`, and `D` are long sequences of letters and numbers etc.

3. Create a new text file (let's call it `backup.json`) with the following contents:
`{"signature":{"iv":"A","ciphertext":"B"},"bookmarks":{"iv":"C","ciphertext":"D"},"is_compressed":true,"is_fresh":false,"version":{"major":0,"minor":1,"release":19,"tag":"a"}}`

Where `A`, `B`, `C`, and `D` are the same as from the previous step.

4. Save that `backup.json` file.
5. Install PB again, choose a password and unlock.
6. Go to PB's options page.
7. Try and import `backup.json` that we have created using the same password
   you had at your old installation.

Let me know how that goes.

**Comment by dammit1964** [comment]
Success! Thank you.
