### ISSUE TITLE
Private Bookmarks Mysteriously Disappeared!

### ISSUE THREAD

**Issue by luv2go37** [rharel/webext-private-bookmarks#127]
For suggestions, please fill in:
 - What you wish you could do and why: ?
 - What you propose as a solution: ?

For bug reports, please fill in:
 - Firefox version:   70.0.1
 - Operating system:  Mac OS 10.14.6 
(Mojave)
 - Steps to reproduce: Upon awakening computer from 'sleep,' and going to Private Mode in Firefox, the Private Bookmarks folder under Other Bookmarks, had disappeared.
 - What was the expected behavior: Bookmarks would be retained based on past experience, as I did nothing different.
 - What was the actual behavior: They mysteriously disappeared.  My SSD is routinely backed up to External HDD to Apple Mac Timeline.  Can I restore the Private Bookmarks folder?  If so, how, please.  Thanks in advance.

It is assumed that you are using the latest version of Private Bookmarks.  I am.  Just downloaded the extension within the last week or so.

**Comment by rharel** [comment]
Not exactly sure I follow. The folder is supposed to be there only when unlocked, are you saying that you cannot unlock?

**Comment by luv2go37** [comment]
*I can unlock.  Folder is there when unlocked, however it was unpopulated
with bookmarks.  Had to re-register.  Same PW allowed as before, but
original Folder with bookmarks was gone. *

*May I find them in my hard drive backups on my external hard drive?*

**Comment by rharel** [comment]
0. In your backup, locate and open your Firefox profile folder, on Mac I think it should be under `Users/<username>/Library/Application Support/Firefox/Profiles/`
1. In your backup profile folder, under `browser-extension-data\private-bookmarks@rharel` there should be a file `storage.js`. Open it in a plain text editor (like notepad or notepad++)
2. Inside you should see something like:
`{...,"back_folder":{"signature":{"iv":"A","ciphertext":"B"},"bookmarks":{"iv":"C","ciphertext":"D"},...}}`

Where `A`, `B`, `C`, and `D` are long sequences of letters and numbers etc.

3. Create a new text file (let's call it `backup.json`) with the following contents:
`{"signature":{"iv":"A","ciphertext":"B"},"bookmarks":{"iv":"C","ciphertext":"D"},"is_compressed":true,"is_fresh":false,"version":{"major":0,"minor":1,"release":19,"tag":"a"}}`

Where `A`, `B`, `C`, and `D` are the same as from the previous step.

4. Save that `backup.json` file.
5. Unlock PB
6. Go to PB's options page.
7. Try and import `backup.json` that we have created using the same password
   you had at your old installation.

Let me know how that goes.

**Comment by luv2go37** [comment]
*Thanks!  I'm researching.  So far, the path to the .json file may be
different than you thought on the Mac.  [JavaScript Object Notation]*


*My issue may relate to JavaScript issues, or if the .json file extension
is in the same format.  I'll let you know if and when I am able to solve
this.  It is not a major problem, but I'd like to figure it out.*

*https://support.mozilla.org/en-US/questions/1229961
<https://support.mozilla.org/en-US/questions/1229961>*


*When you refer to PB's options page, may I assume you mean the Private
Bookmarks Preferences tab where Import is found?*

**Comment by rharel** [comment]
You can find your profile folder location through Main Menu Button => Help => Troubleshooting Information => Application Basics => Profile Folder

The links you provided seems to discuss Firefox' bookmarks backup. PB's bookmarks are stored in a different file, the one I mentioned in my previous message.

Yes, this is also the page that opens through the little gear icon in PB's main menu.

**Comment by luv2go37** [comment]
*Thanks!*

*It appears, from my backup, that Firefox has shifted their info from
Firefox to Mozilla in Firefox 70.0.1 (64 bit).*

*It first appears 10/31/2019, and was not in the backups from 10/25,28,29,&
30/2019.*

*The path is Users/<username>/Library/Application
Support/Mozilla/Extensions/{ec8030f7-...a9e97384}*


*The name Firefox does not appear in the branching from the Application
Support.  Perhaps it did in previous Firefox versions prior to their shift
from 32 bit to 64 bit.*

*Any thoughts?*

*Roger*

**Comment by rharel** [comment]
Unfortunately I'm not familiar with Mac.  Is there no `Users/<username>/Library/Application
Support/Mozilla/Profiles` folder?
You could also try to perform a search for the `private-bookmarks@rharel` folder I previously mentioned.

**Comment by luv2go37** [comment]
*Hih Raoul—*


*There is not.  *

*There is a Users/<username>/Library/Application
Support/Mozilla/Extensions/{ec8030f7-...a9e97384}*

*This is what appears when I do a Spotlight search on the Mac.*

*The word "error" doesn't seem good to me!*

[image: UNADJUSTEDNONRAW_thumb_9fe7.jpg]

*It may be permanently lost.  I've wondered if there are possible glitches
with the Mac OS X operating system, Firefox shifting from 32-bit to 64-bit
app, and/or updating to 70.0.1.*

*version.*

*I really appreciate your work-effort in developing your Extension for
Firefox.  Thank you so much!  Likely, my diligent backups in the past will
not be able to recover what was saved, based on my failure to track down
the folder you suggested.*

*Thanks!*

*Roger*

**Comment by rharel** [comment]
Main Menu Button => Help => Troubleshooting Information => Application Basics => Profile Folder might give a clue where your profile might be, but if it isn't there in your backups there's not much further I can do from here.

Sorry I couldn't be of more help. All I can recommend is to export backups from PB's options page next time. Cheers.

**Comment by luv2go37** [comment]
*Raoul—*

*You would just export the backup from PB's options page to "a plain text
editor like notepad or notepad++" as you mentioned at the outset, as
opposed to the Firefox (Default) which then pops up in the prompt?*


*With your answer, I'll then bow out.  Many thanks for your help. *

*I know Firefox Add-Ons and Extensions can be tricky at times.  At least
I'll know for the future.*

*Roger*

**Comment by rharel** [comment]
It doesn't matter much the name or extension you export it as. The data inside is the same. It's just that with an export from PB's options page you get to choose where to save the file to, such that in the event of you needing to restore you'll know exactly where it is as opposed to your current issue. You can even do a test run by exporting the file, then trying to import it right away to verify this works. N.B. this exports only your Private Bookmarks, not all your bookmarks. Cheers.

**Comment by luv2go37** [comment]
Understood. 

Will do. 

Many thanks!

Roger
