### ISSUE TITLE
All private bookmarks exposed!

### ISSUE THREAD

**Issue by Origitalus** [rharel/webext-private-bookmarks#129]
- Firefox version: 72.0.1 (64-bit)
 - Operating system: Microsoft Windows 10 Education
 - Steps to reproduce: Startup Computer and Firefox after having Shutdown everything the day before while having the bookmarks unlocked.
 - What was the expected behavior: Private Bookmarks hidden in the invisible folder until I unlock.
 - What was the actual behavior: All the private bookmarks (over 1000) are visible at the bottom of the Bookmarks Menu Folder.

**Comment by rharel** [comment]
Are you a Firefox Sync user?
