### ISSUE TITLE
The import operation failed.

### ISSUE THREAD

**Issue by GHfero** [rharel/webext-private-bookmarks#131]
I have installed Private Bookmarks on Firefox 72.0.2. I enter my password to unlock successfully, However, when I attempt to import bookmarks, I receive this error:

bookmarks-2020-01-22.json: The import operation failed.

I have closed and reopened the browser, but nothing works to fix this problem. The bookmarks I want to import are previous, unencrypted bookmarks.

How do I import bookmarks?

![image](https://user-images.githubusercontent.com/60197020/72987430-01aee900-3db0-11ea-8a07-9f556395120f.png)

**Comment by rharel** [comment]
If you open the backup file with a text editor like notepad, do the contents resemble the following...

`{"signature":{"iv":"A","ciphertext":"B"},"bookmarks":{"iv":"C","ciphertext":"D"},"is_compressed":true,"is_fresh":false,"version":{"major":0,"minor":1,"release":19,"tag":"a"}}`

...Where `A`, `B`, `C`, and `D` are long sequences of letters and numbers etc?
Also, is this problem specific to this particular backup file or all backups?

**Comment by GHfero** [comment]
This happens with any ,json backup I make. I have tested this repeatedly.

Here is the beginning of the file:

{"guid":"root________","title":"","index":0,"dateAdded":1522544323725000,"lastModified":1579979538127000,"id":1,"typeCode":2,"type":"text/x-moz-place-container","root":"placesRoot","children":[{"guid":"menu________","title":"menu","index":0,"dateAdded":1534735544609000,"lastModified":1579979538127000,"id":2,"typeCode":2,"type":"text/x-moz-place-container"

The file is large, 802 KB.

Thanks for your assistance.

**Comment by rharel** [comment]
The import function is designed to work with backups exported via the Private Bookmarks option page. If you're trying to import another type of bookmarks file (like from Firefox' or another browser's regular bookmark backup mechanism), the import failure is to be expected.

If your goal is to move the bookmarks in that file into Private Bookmarks, I suggest:
1. Importing via the browser itself
2. Unlocking Private Bookmarks
3. Moving the bookmarks into the PB folder.
4. Locking.

Cheers.

**Comment by GHfero** [comment]
Where is the Private Bookmarks folder?

**Comment by rharel** [comment]
While Private Bookmarks is unlocked, the folder appears (by default) under the Other Bookmarks folder. When locked, the folder disappears again. Bookmarks in PB are encrypted while the folder is locked.

If this is regarding either a large number of bookmarks or if they are very important, I encourage you to keep a separate regular browser backup of them somewhere secure too, so that they may always be restored in the event of a bug in PB.

**Comment by GHfero** [comment]
I have a hundreds (maybe thousands) of bookmarks. Can I move them by pasting the .json file into the Private Bookmarks folder or must I enter each one manually?

**Comment by rharel** [comment]
That should not be necessary, simply selecting them all and cut + paste should do the trick. You do need to import the file first via the regular Firefox backup restore feature. It's late where I'm at, I'll have to provide you with detailed instructions at a later time. Cheers.

**Comment by GHfero** [comment]
Thank you Raoul. To reassure you, I am a fanatic about keeping redundant encrypted backups of everything.

**Comment by rharel** [comment]
To import bookmarks using Firefox' restore mechanism:
1. `Ctrl+Shift+B` to open the bookmarks window.
2. At the top of the bookmarks window, select `Import and Backup`
3. Select `Restore...` and then at the bottom `Choose File...`
4. Locate the backup file and restore it.

To move bookmarks in bulk to the Private Bookmarks folder.
1. Unlock Private Bookmarks, the Private Bookmarks folder appears (by default under Other Bookmarks).
2. `Ctrl+Shift+B` to open the bookmarks window.
3. Select all bookmarks/folders you wish to move (Ctrl+A selects all in the current view, or you can shift+click to select ranges of items).
4. Ctrl+X to Cut
5. Right click the Private Bookmarks folder and `Paste`
6. You can now lock Private Bookmarks again.

Let me know how that goes.

**Comment by GHfero** [comment]
Raoul,

Your instructions for getting existing bookmarks into a new Private Bookmarks folder worked for me! Thank you for your assistance.

I have noticed another issue, however. If I select "Disable Private Bookmarks outside of private browsing" and then open a New Private Window, the Private Bookmarks icon no longer appears in the private window.

**Comment by GHfero** [comment]
Raoul,

Sorry! I see now that Private Bookmarks will run in private windows if I allow it to on the Details tab.

**Comment by rharel** [comment]
Glad things worked. Cheers!
