### ISSUE TITLE
Update caused bookmarks to disapear

### ISSUE THREAD

**Issue by Aaron341** [rharel/webext-private-bookmarks#132]
For suggestions, please fill in:
 - What you wish you could do and why: ?
 - What you propose as a solution: Need information on where the bookmarks are stored.  Need a way to decrypt the file using the app and my password.

For bug reports, please fill in:
 - Firefox version: 72.0.2
 - Operating system: Windows 10
 - Steps to reproduce: unknown  Some sort of update happened in Firefox or the app.
 - What was the expected behavior: The app would be able to find the bookmarks because they didn't move.
 - What was the actual behavior: The app asked me to create a password as if I was using it for the first time.  When I asked it to import bookmarks it couldn't read the file.

It is assumed that you are using the latest version of Private Bookmarks. 0.1.19

**Comment by rharel** [comment]
There was no app update. Try reinstalling the app, or 'clear data' from the options page and then import a backup file from before this issue arose. Let me know how that goes. Cheers.
