### ISSUE TITLE
Firefox 74 addon, Windows 10: Keywords bug

### ISSUE THREAD

**Issue by username114** [rharel/webext-private-bookmarks#134]
Hi just wanted to let you know after testing that keywords on a bookmark link is lost during the unlocking-to-locking-unlocking process.

Might not be a massive issue (bookmark search bar), but I think worth nothing and for someone who decides to move bookmarks from privates folder and back to normal bookmarks will be caught unaware.

**Comment by rharel** [comment]
Do you mean the bookmarks tags? Unfortunately Firefox does not let extensions access your tags, that's why they can't be saved. See also previous issue #61 .
