### ISSUE TITLE
Viewable in not private browsing

### ISSUE THREAD

**Issue by slisnotthere** [rharel/webext-private-bookmarks#135]
Hi
When private folder is unlocked in private browsing window  private folder is visible in the non-private browsing window
Is it normal ? And wich configuration must be done to clera this issue.
Thanks for help.

**Comment by rharel** [comment]
It is normal, when unlocked it's a regular bookmark folder and behaves exactly like any other. Firefox does not give extensions a way to prevent folders from being visible in non-private windows, unfortunately.
