### ISSUE TITLE
Private bookmarked pages leaks to "Recently added" bookmark folder

### ISSUE THREAD

**Issue by Zardoz89** [rharel/webext-private-bookmarks#137]
- What you wish you could do and why: ?
Must not leak on the folder "Recently added". It, ruins the whole purpose of this add-on.

 - Firefox version: 76.0.1 64-bit
 - Operating system:  kUbuntu 19.10 eoan
 - Steps to reproduce: Simply bookmark anything on Private bookmarks. 
 - What was the expected behavior: Not show on it !
 - What was the actual behavior: It will be showed on "Recently added" bookmark folder.
- Private Bookmarks version : 0.1.19a

**Comment by rharel** [comment]
See this comment on a similar issue: https://github.com/rharel/webext-private-bookmarks/issues/107#issuecomment-489312844

Note that there might be a small delay between locking the folder and the bookmarks disappearing from the 'recently added' list (on my pc it's a few seconds). If on yours they stay there even long after let me know.

**Comment by Zardoz89** [comment]
I just verified that I was fooled. I copy my old "private" bookmarks to the private bookmarks, and the recently added was showing the latest old "private" bookmarks that I bookmarked.

I just tested bookmarking something new on private bookmarks, and I verify that isn't leaking to recently added.
