### ISSUE TITLE
Does not work at all. 

### ISSUE THREAD

**Issue by mat-ej** [rharel/webext-private-bookmarks#141]
For bug reports, please fill in:
 - Firefox version: 78.0.2 (64-bit) Firefox for Ubuntu canonical 
 - Operating system: ? Ubuntu 18.04.4 LTS
 - Steps to reproduce: ? After installing the extension and restarting firefox, I simply click the star button and I either get no response at all, no way to use the extension or I get some broken window and then on second click I get no response at all
 - What was the expected behavior: application working.
 - What was the actual behavior: Star button does not respond to a click, on rarely. After it does, the password is asked, after the password has been entered the star button stops working again.

It is assumed that you are using the latest version of Private Bookmarks. - Yes latest version 0.1.19a

**Comment by rharel** [comment]
Hmm, did you give it permission to be active in private windows? 
![image](https://user-images.githubusercontent.com/3788700/87852218-659a1080-c900-11ea-8471-a0018c006e76.png)

**Comment by mat-ej** [comment]
my bad, there was some misunderstanding on how it works on my side.
