### ISSUE TITLE
Unreliable - Password Failure

### ISSUE THREAD

**Issue by rayinny** [rharel/webext-private-bookmarks#142]
My very first use of this extension and it was an absolute failure.  Total loss of bookmarks.  I installed the extension, tested that the password was ok by locking and unlocking the vault several times, then added my bookmarks to the vault.  I tested the password again by unlocking and locking several times again.  All seemed fine.  Next day I tried to access the vault and I am locked out.  The password no longer works.  And yes the password I’m using is accurate.  It was stored in a password vault and was copied and pasted or auto-filled on each use.  A data encryption program is absolutely useless unless it is absolutely reliable.  This extension fails that requirement!  I wouldn’t recommend it.  I’ll have to try something else.

**Comment by rharel** [comment]
Unfortunately I cannot solve problems I cannot reproduce on my end. In the extension description and in itself there are many warnings regarding its experimental nature and that making backups of your bookmarks is the way to go. Oh well.
