### ISSUE TITLE
Question : I can not work out how this addon works?

### ISSUE THREAD

**Issue by Adventure4Life** [rharel/webext-private-bookmarks#143]
How do you use this addon... I installed it on FireFox and a purple "star" icon apeared in the addon bar at the top of the browser... now what? I can not click or right click on it.. there is nothing in options I can see to set my password or anything... I tried making some bookmarks and I cna make them and open them without any response from the ad-on. Also none of the keybinds seem to do anything and I can not work out how to edit them either.

How exactly do you use this thing?

**Comment by rharel** [comment]
Did you give it permission to be active in private windows? 
![image](https://user-images.githubusercontent.com/3788700/87852218-659a1080-c900-11ea-8471-a0018c006e76.png)

Once you do that, open a private window and try clicking on the star button. It should open the main panel and let you choose a password.
