### ISSUE TITLE
Oops with no further explanation

### ISSUE THREAD

**Issue by ManuelDTW** [rharel/webext-private-bookmarks#19]
I just downloaded the extension and created a password. Then when I attempt to unlock it for the first time, I get the error message, "Oops, there was an error" but no further explanation.

**Comment by rharel** [comment]
I assume the extension's version you downloaded was 0.0.7? What version of Firefox are you using?

**Comment by rharel** [comment]
I managed to reproduce. Looking into it.

**Comment by rharel** [comment]
Should be fixed in the latest release (0.0.9).
