### ISSUE TITLE
When I close Firefox, I loose my bookmarks prior to the current ones created on 4/7 and 4/8/2022.

### ISSUE THREAD

**Issue by dphjr1** [rharel/webext-private-bookmarks#190]
For suggestions, please fill in:
 - What you wish you could do and why: ?
 - What you propose as a solution: ?
.
For bug reports, please fill in:
 - Firefox version: ?
 - Operating system: ?
 - Steps to reproduce: ?
 - What was the expected behavior: ?
 - What was the actual behavior: ?

It is assumed that you are using the latest version of Private Bookmarks.

**Comment by rharel** [comment]
Without a way for me to replicate this there's not much I can do unfortunately.
