### ISSUE TITLE
Feature Request - Sub-folders

### ISSUE THREAD

**Issue by Pemto** [rharel/webext-private-bookmarks#196]
For suggestions, please fill in:
 - What you wish you could do and why: I need to organize the bookmarks into categories, like we currently do with folders.
 - 
 - What you propose as a solution: Sub-folders in the private bookmark folder.  Basically, you could have several sub-folders that only show content when expanded.  Sub-folders would be indented to visually separate from other bookmarks, And the folder title would be a bolder font.  Or use the Firefox default look and feel.

I am surprised you can't do this already, so if it is doable, let me know.  Also, maybe add it to the description on the addon page.

Thanks

**Comment by rharel** [comment]
Should already be doable, just create sub folders inside the private bookmarks folder after you unlock, unless I'm misunderstanding.

**Comment by Pemto** [comment]
Sorry, it wasn't working, but it is now.  It might have been a conflict with an add-on that was giving me other troubles.

So this closed.

Thanks
