### ISSUE TITLE
Allow import of several backup files at once

### ISSUE THREAD

**Issue by JohnMiley** [rharel/webext-private-bookmarks#28]
it would be great if there was an option to either scan, or import html or existing bookmarks and encrypt them all, and, just having the password, at the start, as opposed to having to enter one at a time with whilst entering (and confirming) the password

**Comment by rharel** [comment]
I'm sorry I'm not clear on what you are asking for, could you be more specific, or give an example? You can import existing bookmarks, by unlocking, and cut/paste items into the folder. They then become part of the folder, is that what you meant? Also, I don't know what you mean by "importing HTML", what kind of format is that HTML, does it contain a list of bookmarks? I need well-defined specifics.

**Comment by rharel** [comment]
Or do you mean that in the Import section on the options page, you want to be able to import multiple backup files at once with the same password?

**Comment by JohnMiley** [comment]
Hi, yes that's right. It would be great to encrypt multiple bookmarks using the same password, as in maybe bathch process them.

For example, the reason I previously referred to html file import, is that firefox allows you to export your bookmarks into an html format.
If you in turn, could "import" said bookmarks, by way of maybe just logging to the app, then batch processing, it would be an amazing feature to have,
thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by rharel** [comment]
Ah I see. Importing several files with the same password sounds good. But I'm not sure what is the benefit of the HTML import: can't you import through Firefox, unlock Private Bookmarks, and move the imported bookmarks into the folder, then lock? Why should there be a feature for it through the extension if it is already possible through Firefox is what I'm missing.

**Comment by rharel** [comment]
That is strange. The only reason I can think of why you have problems is that there are maybe A LOT of bookmarks in those folders you try to move. How many bookmarks are there?

**Comment by JohnMiley** [comment]
there were maybe 20, not that many

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by rharel** [comment]
I see. In principle you should be able to move any bookmark item or folder into private bookmarks, (wait a few seconds to let it encrypt it - until the hourglass icon disappears), and then lock as usual. Unfortunately it seems something about your particular configuration/machine is causing problems, but I can't say more than that... sorry.
