### ISSUE TITLE
Additing of the option "move private bookmarks folder to the preferred place".

### ISSUE THREAD

**Issue by Neytrino-OnLine** [rharel/webext-private-bookmarks#34]
Personally I - use Fast Dial for work with my bookmarks (so I don't use the menu, the sidebar or the bookmarks panel). So it is inconvenient - to do additional actions to reach the folder with private bookmarks... I think it would be convenient - if the user could set an arrangement private bookmarks folder in settings (to move it from "other bookmarks", to "bookmarks menu" folder (for example))...

**Comment by rharel** [comment]
You'd be glad to know then that something like this is already planned for the next release: i.e. if you move the Private Bookmarks folder somewhere else, the extension will remember where you placed it and next time it will be spawned there, will that address your suggestion? Thanks for the feedback.

**Comment by Neytrino-OnLine** [comment]
**rharel**, yes, it is healthy! I tried to do it with one of the previous versions, and it worked before the first locking. After an unlocking - the folder has returned back... If you have changed it - it is very good news! (will be wait for updates) :)

**Comment by rharel** [comment]
Good I'm glad :) I am marking this as part of #32 and closing this discussion since we addressed everything.
