### ISSUE TITLE
Add an option to disable password requirements

### ISSUE THREAD

**Issue by Neytrino-OnLine** [rharel/webext-private-bookmarks#35]
Personally I - not really like long passwords for things like this, I would prefer to use the short password with digits (1234 for example). But I understand that it can cause some security problems. So, there could be solution works like this:
If I choose the password "1234", extension automatically adds to if something like "a1b2" so actually the password will be such "1234a1b2". It will allow users to use the preferred password and won't break protection of private data...

**Comment by rharel** [comment]
Hmm... I think a better option is to have a checkbox in the options page that allows opt-in for unrestricted passwords - without length limit and character requirements. I'll think about it.

**Comment by Neytrino-OnLine** [comment]
Ok, thanks.
