### ISSUE TITLE
Option to disable the nav-bar button.

### ISSUE THREAD

**Issue by StormFX** [rharel/webext-private-bookmarks#36]
Would it be possible to get an option to disable the "Bookmark this page privately" button on the nav-bar (address bar) or at least make it removable via context menu? ("Remove from Toolbar" is disabled)

**Comment by rharel** [comment]
I'm on Firefox 58 Beta 5 and there is an option in the context menu to "Don't show in Address Bar". So it seems a fix is on the way.

**Comment by StormFX** [comment]
Ah, so it's a Firefox bug?

**Comment by rharel** [comment]
I don't know. Maybe it was unintentional on their part, or perhaps intentional and then they realized it was a mistake.
