### ISSUE TITLE
Must bookmarks be contained in a folder?

### ISSUE THREAD

**Issue by Wildchild009** [rharel/webext-private-bookmarks#48]
Is there any way that I can set it up so that when I type in my password, all of the private bookmarks which I have set will show up (not in an inside of a folder format) sprawled across my Bookmarks Tab. Can I do that?

**Comment by rharel** [comment]
There are both technical (relating to what Firefox allows extensions to do with bookmarks) and performance reasons for the current design (if you are interested I could go into details), so what you request is not possible at the moment: being inside a folder is currently the only way to efficiently detect which bookmarks are private and also allows for quick lock-time.

However, if what you are looking for is a way to conveniently view all private bookmarks without having to open the Bookmarks Sidebar, here is what I suggest:
1. Unlock your private bookmarks.
2. Drag the Private Bookmarks folder to inside the Bookmarks Toolbar.
3. Lock.
4. From now on when you unlock Private Bookmarks will appear in the Toolbar (it remembers the last place you locked it from).

Let me know if that helps, and happy new year!
