### ISSUE TITLE
0.1.13 cannot get past choose a password

### ISSUE THREAD

**Issue by ruphskunk** [rharel/webext-private-bookmarks#49]
Installed add-on ok
open private window
purple star shows up
click star, 'choose a password' appears
click 'choose a password'
two fields are presented, no buttons
enter same password twice that meets criteria.
press return...
nothing happens...no changes to 'change a password' dialog box, except now fields have dots.

Firefox Developers version 58.0b14 (64-bit)
Private Bookmarks 0.1.13
Windows 10 (64-bit)

**Comment by rharel** [comment]
Interesting, but I cannot reproduce... Are you sure the password meets the criteria (no letters with accents, or other special characters)? Once both checkmarks are green next to the password fields a `Confirm` button should appear. Does this happen regardless of what password you try or for some specific one?

**Comment by ruphskunk** [comment]
NM...just notice that periods(.) are not valid characters. Sorry to trouble you.

**Comment by rharel** [comment]
No problem, I'll look into adding dots to the allowed characters in the next release
