### ISSUE TITLE
Sighs ((

### ISSUE THREAD

**Issue by xevidencex** [rharel/webext-private-bookmarks#54]
I've always dreamed to keep private bookmark folders password protected, but you're condemning people who still respect 20 years of mozilla addons development by not allowing a version working with peevious builds & architecture like v44.0.2, the latest firefox version that supports almost all addons besides some webextensions..

if only a build for 40.* up to 45 existed, that would be amazing

I just don't care about encryption, all i want is a password so a bookmark folder
finally opens without playing with data in the background. just a locking feature
with a pass.

**Comment by rharel** [comment]
Again, as I've said in my response to your review, I am sorry but this is unreasonable. It sounds to me like your argument is with the developers of Firefox for choosing to go down the WebExtension path. I do not have the resources to support both old & new versions. Therefore, if I have to make the choice it will always be for the new versions for the reasons I listed in my response to your review.

Again, apologies but that is my final stance on this.
