### ISSUE TITLE
Add the ability to customize command shortcuts

### ISSUE THREAD

**Issue by rharel** [rharel/webext-private-bookmarks#55]
Once Firefox [bug 1421811](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) lands extensions will have the option to update their command shortcuts. We should add a section to the options page that allows that.

See also: #51

**Comment by rharel** [comment]
It seems this will be available starting from Firefox 60.

**Comment by FatOrangutan** [comment]
[Firefox 63 now allows ctrl+alt+key shortcuts too](https://bugzilla.mozilla.org/show_bug.cgi?id=1364784). Would be nice if you could add support for that.

**Comment by rharel** [comment]
Filed as #71.
