### ISSUE TITLE
Does not work when I upgraded to Firefox 59.0.03 64 bit

### ISSUE THREAD

**Issue by yhnujmik** [rharel/webext-private-bookmarks#64]
For suggestions, please fill in:
 - What you wish you could do and why: ?
 - What you propose as a solution: ?

For bug reports, please fill in:
 - Firefox version: ?
 - Operating system: ?
 - Steps to reproduce: ?
 - What was the expected behavior: ?
 - What was the actual behavior: ?

It is assumed that you are using the latest version of Private Bookmarks.

**Comment by rharel** [comment]
I'll need more details than that... What does not work? What is the behavior you experience? Is it a fresh install of PB? Do you need help restoring your bookmarks from a backup (if you made any)?

**Comment by yhnujmik** [comment]
It no longer encrypts the bookmarks. It is not a fresh install of PB. Both my computers experienced the same error when I upgraded Firefox. My operating system on both of my computers is Windows 7 Pro.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rharel** [comment]
Please be more specific. By "no longer encrypts" what do you mean? Do you mean that your password no longer works? Or does everything work but the file where the extension stores its data does not seem to be encrypted?

**Comment by yhnujmik** [comment]
The latter. My password works, however the bookmarks that were encrypted before are visible (unencrypted) without applying the password.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rharel** [comment]
So what happens when you unlock? Does a second folder appear? Or does the existing folder get filled with duplicated bookmarks? Or something else?

 - You could try to first make a new backup of your private bookmarks from the option page (to be safe).
 - Then delete the private bookmarks folder (which if I understand correctly, is always visible, even when it is supposed to be locked).
 - Then try to unlock and lock again and see if the folder appears/disappears as usual.

**Comment by yhnujmik** [comment]
It simply no longer encrypts. I am going to examine the bookmarks more carefully and will try and find differences when I input the password. I will email you with anything I can discover.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yhnujmik** [comment]
It appears that when I updated Firefox, it caused your software to create a duplicate private folder and one of the private folders was now accessible without encryption or password. I folded the newly created private folder into the older private folder and this appears to have corrected the problem.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yhnujmik** [comment]
By the way, I utilize the Opera browser as well. Does your product function with the Opera Browser utilizing Windows 7 Pro?

Thank you

Richard

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rharel** [comment]
I developed and tested it solely on Firefox, so I doubt it will work on
other browsers. It might not take too much work to make an opera-friendly
version, but I don't have enough free time to check that in the near future.

Best,
Raoul

**Comment by yhnujmik** [comment]
Are you at MIT?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rharel** [comment]
Nope, I'm at the Netherlands.

**Comment by yhnujmik** [comment]
I have a BSEE and an MSEE and only took Fortran, Basic and Assembly courses.
I am lost in todays software development.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yhnujmik** [comment]
I am sorry to say that the problem is back when I updated Firefox. When I open a private browser all "private bookmarks" are shown without inputing the password. Secondarily a new private bookmark folder has now appeared and is available to be opened without a password. I believe this folder is a duplicate. Regrettably this software does not function correctly and I will remove it from my computer. I am using Firefox 60.0.1

Thank you

Richard

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rharel** [comment]
Alright no problem, thanks letting me know. Looks like something on your
particular machine / Firefox installation is causing problems. I wish I
could reproduce it but had no luck so far. Have a good one, Raoul

**Comment by rharel** [comment]
I thought about it some more and I think that the problem might be in Firefox Sync. More specifically, I suspect that if you have Firefox Sync syncing your bookmarks, and you perhaps switch between devices while your Private Bookmarks are unlocked, or if you close a device before it can sync the "locking" to the others, then bookmarks might reappear unexpectedly. I have opened a separate issue (#66) to track this where I will try to confirm and work on a solution. Cheers.

**Comment by yhnujmik** [comment]
Hi Raoul,

I do not utilize Firefox Sync. Even though I have a BSEE and MSEE, I am rather unsophisticated when it comes to my computers.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rharel** [comment]
I'll keep thinking. Raoul

**Comment by yhnujmik** [comment]
I wonder if it is this computer. Hard to imagine but possible.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
