### ISSUE TITLE
Error during browser action initialization

### ISSUE THREAD

**Issue by kacy559** [rharel/webext-private-bookmarks#69]
For suggestions, please fill in:
 - What you wish you could do and why: ?
 - What you propose as a solution: ?

For bug reports, please fill in:
 - Firefox version: ?
 - Operating system: ?
 - Steps to reproduce: ?
 - What was the expected behavior: ?
 - What was the actual behavior: ?

It is assumed that you are using the latest version of Private Bookmarks.

**Comment by kacy559** [comment]
Can't open and view private book marks and folders

**Comment by rharel** [comment]
If you have made backups, you can try to restore them through the steps outlined here: https://github.com/rharel/webext-private-bookmarks/issues/67

Cheers, Raoul
