### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by Freemason23** [rharel/webext-private-bookmarks#70]
For suggestions, please fill in:
 - What you wish you could do and why: ?
 - What you propose as a solution: ?

For bug reports, please fill in:
 - Firefox version: ?
 - Operating system: ?
 - Steps to reproduce: ?
 - What was the expected behavior: ?
 - What was the actual behavior: ?

It is assumed that you are using the latest version of Private Bookmarks.

Is is possible to recover my password?

**Comment by rharel** [comment]
If you forgot it, then no. But if you are sure you are typing it in correctly and still cannot unlock, you may have the same issue as #67, and you can try the steps I outlined there to restore your bookmarks from a backup (if you've made one).
