### ISSUE TITLE
Error during browser action initialization

### ISSUE THREAD

**Issue by anonkat** [rharel/webext-private-bookmarks#72]
Debug info: `Could not establish connection. Receiving end does not exist.`

^^ Seems your addon is giving you some helpful information automatically. I have never had any issue with it until just 5 minutes ago. I closed the browser and opened ti agian fresh. But, that doesn't even seem, to me, to be the issue. "Receiving end does not exist", to ME, seems like it is reaching out to something somewhere. I didn't know it had to "phone home" to use this. 

Can you advise me of a fix? I have a LOT of bookmarks in there I really do not want to lose.

Thank you for 1) your time and help and 2) making the addon.

Let me know when you can. 🤞

**Comment by anonkat** [comment]
B.T. Dubbs, I am sure you know what your addon error messages look like, but I captured it. I might as well paste it.
![uhoh](https://user-images.githubusercontent.com/41176260/42670050-b39ea58a-8626-11e8-9f81-0df26932a3eb.jpg)

**Comment by anonkat** [comment]
I don't know why I didn't consider this before, but I (now more awake and able to concentrate) I now remembered I backed up the data! I simply disabled it and re-enabled it again, imported data, and it worked beautifully.

As for sync, I do not think I do use that.

Thanks for your fast response and help. Thanks also for the addon itself. It's helpful!

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-

anonkat
E: anonkat@pm.me

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rharel** [comment]
You're very welcome. Cheers, Raoul
