### ISSUE TITLE
Password input fields vanishes right after clicking on "Choose a password"

### ISSUE THREAD

**Issue by 1989gironimo** [rharel/webext-private-bookmarks#78]
- Firefox version: 61.0.1
 - Operating system: Ubuntu 18.04
 - Steps to reproduce: Install, try to set a password
 - What was the expected behavior: Opening up password fields
 - What was the actual behavior: It shows for a very short time and vanishes right after that 
- Using the latest version

**Comment by rharel** [comment]
Does the same thing happen when you try to open the panel in a tab (the default shortcut for this is: Alt+Shift+8)?

**Comment by 1989gironimo** [comment]
That works as expected, a new tab opens where I can choose the password.

**Comment by 1989gironimo** [comment]
That works as expected, a new tab opens where I can choose the password.

**Comment by rharel** [comment]
Then it is most likely a Firefox bug.

**Comment by matt32106** [comment]
same problem here in 18.04, I also have this problem with the Lastpass extension

**Comment by rharel** [comment]
Yep looks that way. Thanks for confirming @matt32106 .

**Comment by rharel** [comment]
Can you still reproduce this @1989gironimo, @matt32106 ?

**Comment by matt32106** [comment]
I was not able to re-test it, I don't remember how to reproduce the issue. Sorry.

**Comment by 1989gironimo** [comment]
I'll report back in a few days, but don't use Ubuntu anymore, so I can't really reproduce it completely.

**Comment by matt32106** [comment]
If you can guide me through the clicks, I can test (still using Ubuntu :)).

**Comment by rharel** [comment]
> 
> 
> If you can guide me through the clicks, I can test (still using Ubuntu :)).

The original report says that it happens after installation, when trying to choose a password from the popup menu. So if you could create a new profile, install PB and check if it still vanishes that'll do it.

**Comment by matt32106** [comment]
I created a new profile, installed the addon. I see no popup menu where I have to choose a password. The register/login window (no popup here) works OK.

**Comment by 1989gironimo** [comment]
Cannot replicate either, seems to be fixed.

**Comment by rharel** [comment]
Thanks guys,
