### ISSUE TITLE
Location of Bookmark File

### ISSUE THREAD

**Issue by jcaliforniar** [rharel/webext-private-bookmarks#82]
I recently upgraded certain parts in my PC, only to find windows needed to reinstall itself. When that occurred, Windows deleted all my apps. I'm now looking to find if there's a way to get my old Private Bookmarks from the windows.old backup directory. I was able to retrieve my standard bookmarks via the standard firefox backup folder there, but couldn't find anything similar for Private Bookmarks. 

Is there a file I can transfer over to regain my Private Bookmarks?

Thanks!

**Comment by rharel** [comment]
Hey. If you have made any backups (using the export buttons in the options page) you can import them. Otherwise you could see if you can find the extension's storage file under your Firefox profile at `windows.old` - for this I refer you to my comments in the very similar issue #47.  Just don't repeat the same mistake that user made and make a copy of the file before experimenting with getting it to load in your new installation of Firefox. Let me know how it goes. Cheers, Raoul

**Comment by jcaliforniar** [comment]
Thanks for the quick response!

I tried the above. Any time I copy over the old extension’s bookmark directory, it looks like firefox overwrites it when launching. In fact, after trying this two times now, when I launch firefox and unlock the bookmarks, it now creates multiple Private Bookmarks folders in my Other Bookmarks directory. 

I also tried deleting the storage file and not replacing it, and it still comes up with my newer profile’s bookmarks, almost like the bookmarks aren’t really stored there. 

Thoughts?

**Comment by rharel** [comment]
Let's try this:
1. Open the `storage.js` from `windows.old` in a plain text editor (like notepad or notepad++)
2. Inside you should see something like:
`{...,"back_folder":{"signature":{"iv":"A","ciphertext":"B"},"bookmarks":{"iv":"C","ciphertext":"D"},...}}`

Where `A`, `B`, `C`, and `D` are sequences of letters and numbers.

3. Create a new text file (let's call it `backup.json`) with the following contents:
`{"signature":{"iv":"A","ciphertext":"B"},"bookmarks":{"iv":"C","ciphertext":"D"},"is_compressed":true,"is_fresh":false,"version":{"major":0,"minor":1,"release":16,"tag":"a","revision":1}}`

Where `A`, `B`, `C`, and `D` are the same as from the previous step.

4. Save that `backup.json` file.
5. Unlock Private Bookmarks.
6. Go to PB's options page.
7. Try and import `backup.json` that we have created using the same password
   you had at your old Firefox installation.

Let me know how that goes.

**Comment by rharel** [comment]
I should have mentioned, between steps 4-5, if you hadn't already, you should choose a password in your new Private Bookmarks and then at step 5 you unlock using it.

**Comment by jcaliforniar** [comment]
That worked! Thanks Rharel!
