### ISSUE TITLE
Bookmarks not encrypted

### ISSUE THREAD

**Issue by kstev99** [rharel/webext-private-bookmarks#88]
Using WATERFOX 56.2.3 the "hidden" bookmarks are easily recognized by searching the text strings within the bookmarks file, places.sqlite that resides in the profile folder.  I haven't tried this on Firefox, so I can't say if the same is true

**Comment by kstev99** [comment]
I apologize.  This is NOT an issue.  I had recently started using a portable version of the browser and the bookmarks file I was seeing was a remnant of the installed version before the add-on was installed

**Comment by rharel** [comment]
See the related issue #81. For me, the entries are deleted from moz_places once the browser closes, but this may be influenced by my browser's data clearing settings.
