### ISSUE TITLE
can't find the Private Bookmarks folder after installing plugin

### ISSUE THREAD

**Issue by danicolaj** [rharel/webext-private-bookmarks#89]
Just downloaded the add on, it's enabled, and according to the docs I should have a Private Bookmarks folder under Other Bookmarks, but there's no such a folder.

using firefox 62.0.3 64-bit, with Adblock plus and Noscript

**Comment by rharel** [comment]
Have you chosen a password and then unlocked using the chosen password? The folder is only there while unlocked.
