### ISSUE TITLE
Bookmarks links are not decrypted 

### ISSUE THREAD

**Issue by Bondiou** [rharel/webext-private-bookmarks#93]
- Firefox version: 65.0b4 
 - Operating system: OS X 10.13.6
 
I type my password. Private Bookmarks process and succeed but bookmarks still encrypted. I can see the bookmarks file and the bookmarks titles but the links stay encrypted. 

I got this  
ext+linkpassword://06WLW3h4eHipehVLrMWku................

**Comment by rharel** [comment]
That's a new one... So I have a few questions:
1. Has this started happening only recently or are you a new user and this is what you experience right after installation?
2. Do you have any other extensions installed that might tinker with bookmark URLs?
3. Are the bookmark URLs not to regular websites but perhaps to pages of another extension?

**Comment by Bondiou** [comment]
1. No. I am not a new user. It was always working. I mean my last try was a few weeks ago and everything was working well.
2. No. I have only some usual extensions as Adblock Plus, Ghostery... 
3. No. It is regular URLs

Two other things who might be important. 

When I try to open a link like "ext+linkpassword://06WLW3h4eHipehVLrMWku................"
the system asks me to choose an application to open it.

Inside the "Private Bookmarks" file, there is a subfile I called "SB" with other URLs which is totally decrypted.

**Comment by rharel** [comment]
I see, so only some bookmarks remain encrypted. From a short search it seems that URLs starting with `ext+linkpassword` are related to the [Link Password](https://addons.mozilla.org/en-US/firefox/addon/link-password/) extension. So my guess would be PB decrypts the bookmarks, but the PB-decrypted version is still encrypted by Link Password and must be decrypted using it as well. Does this ring a bell for you?

**Comment by Bondiou** [comment]
I just downloaded "Link Password" extension and all of the URLs are now decrypted.
I don't understand what happened. I might have tried "Link Password" extension and forgot about it.

Thank you very much for your help and sorry for the trouble.

**Comment by rharel** [comment]
You're very welcome, it was no trouble at all. Cheers.
