### ISSUE TITLE
Make password input discoverable by Kee (KeePass extension for FF & Chrome)

### ISSUE THREAD

**Issue by penenkel** [rharel/webext-private-bookmarks#94]
I use KeePass to store all my passwords and the extension [Kee](https://addons.mozilla.org/de/firefox/addon/keefox/) to (auto-)fill login forms in Firefox.

Of cause I'm also storing my password for PrivateBookmarks in KeePass. Unfortunaly the password input is not picked up/recognized by Kee.

AFAIK Kee picks the inputs it fills by looking for forms named (or with id) "login" and then inputs whose name/id is included in a configurable list.  I do not know if that mechanism only works on "real" websites or if panels created by other addons are also discovered.

I attempted to modifiy this addon by wrapping the password input in `popup_ui/page.html` in a form, but couldn't get it to work immediately. On the other hand I have little expirience in writing extensions, so that is not too supprising.

I would appreciate it if someone would take a stab at this, as it would improve the usabliity of this extension enormously. At least in my book.

**Comment by rharel** [comment]
I think KeePass does not pick it up because `page.html` is a page of an extension and not of a website. I believe Firefox does not allow extension access to pages of other extensions, so unfortunately I do not see a way to fix this.

**Comment by penenkel** [comment]
Yeah, I was afraid that might be the case. Too bad, I really would have liked such a feature.
