### ISSUE TITLE
Bookmarks are not synchronizing

### ISSUE THREAD

**Issue by ImJustMatt** [rharel/webext-private-bookmarks#97]
- Firefox version: 64.0
 - Operating system: Windows 10 Pro 1809
 - Steps to reproduce: N/A
 - What was the expected behavior: Unlock on one computer, add new bookmark, lock. Unlock on another computer, new bookmark will be there.
 - What was the actual behavior: Two computers are maintaining two separate copies of their own private bookmarks for the same Firefox account.

I've tried backing up from one computer, uninstalling the extension from all computers, deleting all the data, reinstalling and restoring the backup. New bookmarks from one computers still do not appear on the other computer.

**Comment by rharel** [comment]
Thanks for the report. Just to make sure: in Firefox Sync options, do you have the Add-ons box checked?

**Comment by ImJustMatt** [comment]
Yes, I have all of the Sync options selected

**Comment by rharel** [comment]
Alright, I'll investigate when I have the time.
