### ISSUE TITLE
How do i decrypt the exported bookmarks manually?

### ISSUE THREAD

**Issue by Geekology101** [rharel/webext-private-bookmarks#98]
For suggestions, please fill in:
 - What you wish you could do and why: Manual Decryption
 - What you propose as a solution: Use code beautify

For bug reports, please fill in:
 - Firefox version: latest
 - Operating system: win 10
 - Steps to reproduce: ?
 - What was the expected behavior: ?
 - What was the actual behavior: ?

It is assumed that you are using the latest version of Private Bookmarks.

**Comment by rharel** [comment]
1. Hash your password into UTF8 bytes using SHA-256. See `digest()`: https://github.com/rharel/webext-private-bookmarks/blob/64f175835cee1bf6a8b0392f90ea46f0f0f38f39/sources/scripts/utilities/cryptography.js#L8
2. Hash the result again using the same method (you will need to convert the bytes back to a hex string first to feed it to `digest()` again, see `from_hex_bytes()`) https://github.com/rharel/webext-private-bookmarks/blob/64f175835cee1bf6a8b0392f90ea46f0f0f38f39/sources/scripts/utilities/string_utilities.js#L64
3. Decrypt `bookmarks.ciphertext` using AES-GCM with `bookmarks.iv` as initialization vector and the doubly hashed password as key. See `decrypt()`: https://github.com/rharel/webext-private-bookmarks/blob/64f175835cee1bf6a8b0392f90ea46f0f0f38f39/sources/scripts/utilities/cryptography.js#L42
3. Decompress the result using LZ decompression. See `decompress()`: https://github.com/rharel/webext-private-bookmarks/blob/64f175835cee1bf6a8b0392f90ea46f0f0f38f39/sources/scripts/utilities/string_utilities.js#L38

Details are in the referenced functions, but if you are unclear on something don't hesitate to ask.
